routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false
]);

Route::get('/', 'ArtikelController@index');
Route::get('/read/{kategori}/{slug}', 'ArtikelController@show'); // This error
Route::get('/kategori/{name}', 'ArtikelController@kategori'); // This error

// This also fine if i put after prefix.
// Route::get('/', 'ArtikelController@index');
// Route::get('/{kategori}/{slug}', 'ArtikelController@show');

Route::resource('post', 'PostController');
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'verified'])->prefix('dashboard')->group(function () {
    Route::get('/', 'Dashboard@index');
    Route::resource('post', 'PostController');
    Route::resource('categori', 'KategoriController');
    Route::delete('hapus/{id}', 'PostController@destroy');
    
    Route::view('role', 'role');
    Route::get('role', function(){
        return view('role');
    });
});
Route::prefix('demo')->group(function () {
    // Route::view('berg', 'laraberg');
});

/*
Route::get('/notif', function() {
    $user = \App\User::first();
    $user->notify(new \App\Notifications\Daftar);
});
*/

app/Http/Controllers/ArtikelController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Post;

use App\Events\PageCounter;

class ArtikelController extends Controller
{
    //
    public function index()
    {
        //Webmaster
        /*
        $datas = Webs::all();
        foreach($datas as $data){
            config(['seotools.meta.webmaster_tags.'.$data->name.'' => $data->value]);
        }
        */

        $posts = Post::latest()
            ->where('artikel_status', 'publish')
            ->where('tipe_konten', '<>', 'quote')
            ->where('kategori', '<>', 'quote')
            ->simplepaginate(10);
        return view('artikel.index', compact('posts'));
        
    }

    public function show($kategori, $slug)
    {
        //
        $post = Post::where('slug', $slug)->where('kategori', $kategori)->firstorfail();
        config(['meta.title' => $post->judul ]);
        config(['meta.description' => $post->tldr ]);
        config(['meta.image' => $post->image_feature]);
        config(['meta.author' => $post->user->name]);
        config(['meta.twitter_site' => '@ade_fatality']);
        config(['meta.keywords' => $post->keyword]);
        config(['meta.fb_app_id' => 'adasda']);
        
        event(new PageCounter($post)); //trigger event

        return view('artikel.artikel', compact('post'));
    }

    public function kategori($name = 'artikel')
    {
        //
        
        $data = Post::latest()->where('kategori', $name)->simplepaginate(5);
        
        if( count($data) > 0 ){
            return view('artikel.kategori', compact([
                'name',
                'data'
            ]));
        } else {
            return view('artikel.no_kategori');
        }
    }

}

resources/views/artikel/app.blade.php
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Akubagi</title>
        


        {{--
        <link rel="icon" href="{{ url('HatchfulExport-All/favicon.png') }}">
        <link rel="stylesheet" href="{{ asset('bs4/css/bootstrap.min.css') }}">
        <link rel="stylesheet" href="{{ asset('fonts/font.css') }}">
        --}}
        <link rel="stylesheet" href="{{ asset('css/app.css')}}">
        
        <style>
            body{
                font-family: "Gudea";
                padding-top: 80px;
                background-color: #f8fafc;
            }
            
                    
            .unsrink{
                min-height: 50px !important;
                transition: 0.5s;

            }
            .navbar{
                min-height: 80px;
                transition: 0.5s;
            }
            p.card-text{
                font-size: 20px !important;    
            }
            .card-title{
                font-family: 'Gudea Bold';
            }
            
            .heading{
                /* font-family: 'Gudea Bold'; */
                color: #0A91AB !important;
            }
            
            a {
                color: #0A91AB !important;
                text-decoration: none;
                background-color: transparent;
                -webkit-text-decoration-skip: objects;
            }
            
            a:not([href]):not([tabindex]) {
                color: inherit;
                text-decoration: none;
            }
            a:not([href]):not([tabindex]):hover, a:not([href]):not([tabindex]):focus {
                color: inherit;
                text-decoration: none; 
            }
            
            a:not([href]):not([tabindex]):focus {
                outline: 0;
            }

            .bg-primary { 
                background: #77A9BC !important;
            }
            
            blockquote {
                font-family: 'PlayfairDisplay-Medium';
                font-size: 30px !important;
                color: white;
            }
            .blockquote-footer {
                display: block;
                font-size: 16px !important;
                color: white;
            }
            p{
                font-size: 20px;
            }
            .btn-outline-success {
                color: #0A91AB;
                border-color: #0A91AB;
            }
            .btn-outline-success:hover {
                color: #fff;
                background-color: #0A91AB;
                border-color: #0A91AB;
            }
        </style>
    </head>
    <body>
        @include('artikel.navbar')
        
        @yield('content')
        
        <script src="{{ asset('js/app.js')}}"></script>
        <script>
            
            jQuery( document ).ready(function() {
                $(window).scroll(function(){
                    $('.topnav').toggleClass('unsrink', $(this).scrollTop() > 90);
                });
            });
            
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        
    </body>
</html>

resources/views/artikel/artikel.blade.php
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Akubagi - {{ $post->judul }}</title>
        
        @include('meta::manager')
    
        <link rel="icon" href="{{ url('HatchfulExport-All/favicon.png') }}">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
        <link rel="stylesheet" href="{{ asset('fonts/font.css') }}">
        <link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
        
        
        <style>
            body {
                background-color: #F8FAFC;
                font-family: 'Lato Regular';
            }
            
        </style>
    </head>
    <body>
        @include('artikel.navbar')
        <div class="container pt-4 pb-4 mb-2">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    
                    <div class="d-flex align-items-center">
                        <img class="rounded-circle" src="http://localhost:8000/HatchfulExport-All/sequare_44.png" width="50">
                        <h5 class="ml-3 author">{{$post->user->name}} <span class="d-block"><small>Diterbitkan {{ $post->created_at->diffForHumans() }} di <a href="/kategori/{{ $post->kategori }}">{{ $post->kategori }}</a>&middot;</small></span>
                        </h5>
                    </div>
                    
                    <h1 class="display-4 secondfont pt-4">{{ $post->judul }}</h1>
                    <p class="tldr">
                    @if ( $post->tldr != 'null')
                        {{ $post->tldr}} 
                    @endif
                    </p>
                </div>

            </div>

            <div class="row justify-content-center pb-4">
                <div class="col-md-8">
                    <article class="article-post">
                        {!! $post->konten !!}
                    </article>
                    <hr>
                    @auth
                    <i class="fas fa-pen"></i>  <a href="{{ route('post.edit', $post->id)}}">Edit</a>
                    @endauth
                </div>

            </div>
            

            <div class="row justify-content-center pt-4 pb-4">
                <div class="col-md-8">
                    <div id="disqus_thread"></div>
                </div>
            </div>

        </div>
        
        <script src="{{ asset('js/app.js') }}"></script>
        <script>
            
            jQuery( document ).ready(function() {
                $(window).scroll(function(){
                    $('.topnav').toggleClass('unsrink', $(this).scrollTop() > 90);
                });
            });
            
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        
    </body>
</html>

resources/views/artikel/index.blade.php
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Akubagi</title>
        
        
    
        <link rel="icon" href="{{ url('HatchfulExport-All/favicon.png') }}">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
        <link rel="stylesheet" href="{{ asset('fonts/font.css') }}">
        
        
        <style>
            body{
                background-color: #F8FAFC;
            }
            
        </style>
    </head>
    <body>
        @include('artikel.navbar')
        <div class="container pt-4 pb-4 mb">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <h1 class="heading">Semua Artikel</h1>
                    @foreach($posts as $post)
                    <div class="card mb-3 shadow-sm border-0">
                        <div class="card-body">
                            <div class="mb-3 d-flex justify-content-between">
                                <div class="pr-3">
                                    <h2 class="card-title title">
                                    <a class="url" href="/read/{{ $post->kategori }}/{{ $post->slug }}">{{ $post->judul }}</a>
                                    </h2>
                                    <p class="card-text">{{ $post->tldr }}</p>
                                    <div class="card-text">
                                        Diterbitkan {{ $post->created_at->diffForHumans() }} di <a href="/kategori/{{ $post->kategori }}">{{ $post->kategori }}</a>.
                                    </div>
                                </div>
                                @if( empty($post->image_feature) )
                                <img height="120" src="{{ url('/HatchfulExport-All/linkedin_banner_image_2.png') }}">
                                @else
                                <img height="120" src="{{ $post->image_feature }}">
                                @endif
                            </div>
                        </div>
                    </div>
                    
                    @endforeach
                    {{ $posts->links() }}
                </div>
            </div>
        </div>
        
        <script src="{{ asset('js/app.js') }}"></script>
        <script>
            
            jQuery( document ).ready(function() {
                $(window).scroll(function(){
                    $('.topnav').toggleClass('unsrink', $(this).scrollTop() > 90);
                });
            });
            
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        
    </body>
</html>

resources/views/artikel/kategori.blade.php
<!doctype html>
<html lang="en" class="h-100">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Akubagi</title>
        
    
        <link rel="icon" href="{{ url('HatchfulExport-All/favicon.png') }}">
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
        <link rel="stylesheet" href="{{ asset('css/custom.css') }}">
        <link rel="stylesheet" href="{{ asset('fonts/font.css') }}">
        
        
        <style>
            body{
                background-color: #F8FAFC;
            }
            
        </style>
    </head>
    <body>
        @include('artikel.navbar')
        <div class="container pt-4 pb-4 mb">
            <div class="row justify-content-center">
                <div class="col-md-10">
                    <h1 class="heading">Kategori {{ $name }}</h1>
                    @foreach($data as $post)
                    <div class="card mb-3 shadow-sm border-0">
                        <div class="card-body">
                            <div class="mb-3 d-flex justify-content-between">
                                <div class="pr-3">
                                    <h2 class="card-title title">
                                    <a class="url" href="/read/{{ $post->kategori }}/{{ $post->slug }}">{{ $post->judul }}</a>
                                    </h2>
                                    <p class="card-text">{{ $post->tldr }}</p>
                                    <div class="card-text">
                                        Diterbitkan {{ $post->created_at->diffForHumans() }} di <a href="/kategori/{{ $post->kategori }}">{{ $post->kategori }}</a>.
                                    </div>
                                </div>
                                @if( empty($post->image_feature) )
                                <img height="120" src="{{ url('/HatchfulExport-All/linkedin_banner_image_2.png') }}">
                                @else
                                <img height="120" src="{{ $post->image_feature }}">
                                @endif
                            </div>
                        </div>
                    </div>
                    
                    @endforeach
                    {{ $data->links() }}
                </div>
            </div>
        </div>
        
        <script src="{{ asset('js/app.js') }}"></script>
        <script>
            
            jQuery( document ).ready(function() {
                $(window).scroll(function(){
                    $('.topnav').toggleClass('unsrink', $(this).scrollTop() > 90);
                });
            });
            
        </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        
    </body>
</html>

resources/views/artikel/navbar.blade.php
<nav class="topnav navbar navbar-expand-lg navbar-light fixed-top bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            <img src="{{ asset('HatchfulExport-All/sequare.png') }}" alt="" height="30" width="30">
        </a>

        <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="#">Project</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Resources</a>
                </li>
            </ul>
            {{--
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0 mr-sm-2" type="submit">Search</button>
            </form>
            --}}
            @auth
            <div class="dropdown">
                <button class="btn dropdown-toggle mr-sm-2" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ Auth::user()->name }} <span class="caret"></span>
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <a class="dropdown-item" href="/dashboard/post/create">Add Post</a>
                    <a class="dropdown-item" href="/dashboard/index">Dashboard</a>
                    <a class="dropdown-item" href="/dashboard/profile">Profile</a>
                    <div class="dropdown-divider"></div>

                    <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">{{ __('Logout') }}</a>

                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>
            @endauth

        </div>
    </div>
</nav>