routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false
]);

Route::get('/', 'ArtikelController@index');
Route::get('/read/{kategori}/{slug}', 'ArtikelController@show'); // This error
Route::get('/kategori/{name}', 'ArtikelController@kategori'); // This error

// This also fine if i put after prefix.
// Route::get('/', 'ArtikelController@index');
// Route::get('/{kategori}/{slug}', 'ArtikelController@show');

Route::resource('post', 'PostController');
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'verified'])->prefix('dashboard')->group(function () {
    Route::get('/', 'Dashboard@index');
    Route::resource('post', 'PostController');
    Route::resource('categori', 'KategoriController');
    Route::delete('hapus/{id}', 'PostController@destroy');
    
    Route::view('role', 'role');
    Route::get('role', function(){
        return view('role');
    });
});
Route::prefix('demo')->group(function () {
    // Route::view('berg', 'laraberg');
});

/*
Route::get('/notif', function() {
    $user = \App\User::first();
    $user->notify(new \App\Notifications\Daftar);
});
*/

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Kategori extends Model
{
    //
    use SoftDeletes;
    
    protected $fillable = [
        'nama',
        'slug',
        'keterangan',
    ];
}

app/Http/Controllers/Dashboard.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class Dashboard extends Controller
{
    //
    public function index(){
        return view('dashboard.index');
    }
}

app/Http/Controllers/KategoriController.php
<?php

namespace App\Http\Controllers;

use App\Kategori;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Str;

class KategoriController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $result = Kategori::orderBy('judul', 'asc')->get();
        return view('dashboard.kategori.index', compact('result'));

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('dashboard.kategori.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $data = new Kategori;

        //$post->slug = Str::slug($request->judul, '-').'-'.Str::random(6);
        $data->judul    = $request->name;
        $data->slug     = Str::slug($request->name, '-');
        $data->keterangan = $request->keterangan;

        $data->save();

        return redirect('/dashboard/categori')->with('status', 'new categori added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function show(Kategori $kategori)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function edit(Kategori $kategori)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Kategori $kategori)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Kategori  $kategori
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kategori $kategori)
    {
        //
    }
}

resources/views/dashboard/kategori/create.blade.php
@extends('dashboard.app')

@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <form method="post" action="{{ route('categori.store')}}">
                @csrf
                
                <div class="form-group">
                    <div class="input-group input-group-md">
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="name" placeholder="Judul" required>
                    </div>
                </div>
                
                {{--
                <div class="form-group">
                    <div class="input-group input-group-md">
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="slug" placeholder="URL bersifat opsional">
                    </div>
                </div>
                --}}

                
                <div class="form-group">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" name="keterangan" placeholder="Ringkasan" required>{{ old('ringkasan') }}</textarea>
                </div>
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/dashboard/kategori/index.blade.php
@extends('dashboard.app')

@section('css')
<link rel="stylesheet" href="{{ asset('vendor/DataTables/dataTables.bootstrap4.css') }}">

@endsection
@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th width="25%">Judul</th>
                            <th>Viewer</th>
                            <th width="50%">Kategori</th>
                            <th width="25%">Opsi</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($result as $data)
                        <tr>
                            <td>{{ $data->judul }}</td>
                            <td>{{ $data->slug }}</td>
                            <td>{{ $data->keterangan }}</td>
                            <td>Deleted</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{ asset('vendor/DataTables/datatables.min.js') }}"></script>
<script src="{{ asset('vendor/DataTables/dataTables.bootstrap4.min.js') }}"></script>

<script>

$(document).ready(function() {
    
    $('#dataTable').DataTable({
        lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]]
    });
    
});

</script>
@endsection