routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => false,
    'reset' => false
]);

Route::get('/', 'ArtikelController@index');
Route::get('/read/{kategori}/{slug}', 'ArtikelController@show'); // This error
Route::get('/kategori/{name}', 'ArtikelController@kategori'); // This error

// This also fine if i put after prefix.
// Route::get('/', 'ArtikelController@index');
// Route::get('/{kategori}/{slug}', 'ArtikelController@show');

Route::resource('post', 'PostController');
Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth', 'verified'])->prefix('dashboard')->group(function () {
    Route::get('/', 'Dashboard@index');
    Route::resource('post', 'PostController');
    Route::resource('categori', 'KategoriController');
    Route::delete('hapus/{id}', 'PostController@destroy');
    
    Route::view('role', 'role');
    Route::get('role', function(){
        return view('role');
    });
});
Route::prefix('demo')->group(function () {
    // Route::view('berg', 'laraberg');
});

/*
Route::get('/notif', function() {
    $user = \App\User::first();
    $user->notify(new \App\Notifications\Daftar);
});
*/

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use VanOns\Laraberg\Models\Gutenbergable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    //
    use Gutenbergable;
    use SoftDeletes;

    //protected $table = 'posts';
    protected $fillable = [
        'judul',
        'konten',
        'slug',
        'artikel_tag',
        'artikel_status',
        'image_feature',
        'kategori',
        'tldr',
        'author',
        'page_counter',
        'page_identifier',
        'tipe_konten',
        'keyword'
    ];

    public function user()
    {
        return $this->belongsTo('App\User', 'user_id');
    }

    protected $dates = [
        'deleted_at',
        'updated_at'
    ];
}

app/Http/Controllers/Dashboard.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class Dashboard extends Controller
{
    //
    public function index(){
        return view('dashboard.index');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Illuminate\Support\Str;
use Auth;
use Illuminate\Support\Facades\Validator;
use DataTables;
use App\Kategori;

use GDText\Box;
use GDText\Color;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        if ($request->ajax()) {
            $data = Post::latest()->get();
            return Datatables::of($data)
            ->addIndexColumn()
            ->addColumn('action', function($row){
                $btn = '<a href="/dashboard/post/'.$row->id.'/edit" data-original-title="Edit" class="edit btn btn-primary">Edit</a>';
                $btn = $btn.' <a href="javascript:void(0)" data-toggle="tooltip"  data-id="'.$row->id.'" data-original-title="Delete" class="btn btn-danger deleteProduct" id="delete-user">Delete</a>';
                $btn = $btn.' <a href="/read/'.$row->kategori.'/'.$row->slug.'" class="btn btn-warning" target="_blank">View</a>';
                return $btn;
            })
            ->rawColumns(['action'])
            ->make(true);
        };
        return view('dashboard.post.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        //$kategori = Kategori::all();
        $kategori = Kategori::orderBy('judul', 'asc')->get();
        return view('dashboard.post.create', compact('kategori'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        // return response()->json($request->all());
        $user   = Auth::user();
        
        $image  = $request->file('feature');
        $judul  = $request->judul;

        if($request->hasfile('feature')){
            $namefile   = '/feature/'.bin2hex(random_bytes(32)).'_'.$image->getClientOriginalName();
            $simpan     = $image->move(public_path('feature'), $namefile);
        } else {
            $im         = @imagecreatefromjpeg(public_path('HatchfulExport-All/blank.jpg'));
            $text       = $request->judul;
            $textbox    = new Box($im);
            $textbox->setFontSize(80);
            
            $textbox->setFontFace(public_path('fonts/Gudea/Gudea-Bold.ttf'));
        
            $textbox->setFontColor(new Color(10, 145, 171)); // black
            $textbox->setBox(
                0,  // distance from left edge
                0,  // distance from top edge
                imagesx($im), // textbox width, equal to image width
                imagesy($im)  // textbox height, equal to image height
            );
    
            $textbox->setTextAlign('center', 'center');
            // it accepts multiline text
            $textbox->draw($text);

            $namefile = '/feature/'.Str::slug($request->judul, '-').'.jpg';
            $name = public_path($namefile); //this saves the image inside uploaded_files folder
            imagepng($im, $name, 9);
        }

        $post                   = New Post;
        $post->user_id          = $user->id;
        $post->judul            = $request->judul;
        $post->konten           = $request->konten;
        $post->kategori         = $request->kategori;
        $post->keyword          = $request->keyword;
        $post->slug             = Str::slug($request->judul, '-').'-'.Str::random(6);
        $post->artikel_status   = $request->status;
        $post->tldr             = $request->ringkasan;
        $post->page_identifier  = bin2hex(random_bytes(15));
        $post->image_feature    = $namefile;
        $post->save();        
        
        return redirect('dashboard/post')->with('status', 'Artikel berhasil ditambahkan!');
        
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    //public function edit(Post $post)
    public function edit($id)
    {
        //
        $kategori = Kategori::orderBy('judul', 'asc')->get();
        $post = Post::find($id);
        //return response()->json($data);
        return view('dashboard.post.edit', compact(['post', 'kategori']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    // public function update(Request $request, Post $post)
    public function update(Request $request, $id)
    {
        //

        $user                   = Auth::user();

        $image  = $request->file('feature');
        $judul  = $request->judul;

        $namefile = $request->current_feature;
        
        if($request->hasfile('feature')){
            $namefile   = '/feature/'.bin2hex(random_bytes(32)).'_'.$image->getClientOriginalName();
            $simpan     = $image->move(public_path('feature'), $namefile);
        } else {
            $im         = @imagecreatefromjpeg(public_path('HatchfulExport-All/blank.jpg'));
            $text       = $request->judul;
            $textbox    = new Box($im);
            $textbox->setFontSize(80);
            
            $textbox->setFontFace(public_path('fonts/Roboto_Slab/static/RobotoSlab-Regular.ttf'));
        
            $textbox->setFontColor(new Color(10, 145, 171)); // black
            $textbox->setBox(
                0,  // distance from left edge
                0,  // distance from top edge
                imagesx($im), // textbox width, equal to image width
                imagesy($im)  // textbox height, equal to image height
            );
    
            $textbox->setTextAlign('center', 'center');
            // it accepts multiline text
            $textbox->draw($text);

            $namefile = '/feature/'.Str::slug($request->judul, '-').'.jpg';
            $name = public_path($namefile); //this saves the image inside uploaded_files folder
            imagepng($im, $name, 9);
        }
        
        $post                   = Post::find($id);
        $post->judul            = $request->judul;
        $post->konten           = $request->konten;
        $post->kategori         = $request->kategori;
        $post->artikel_status   = $request->status;
        $post->tldr             = $request->ringkasan;
        $post->keyword          = $request->keyword;
        $post->image_feature    = $namefile;

        $post->update();        
        
        return redirect('dashboard/post')->with('status', 'Artikel berhasil diupdate');
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    //public function destroy(Post $post)
    public function destroy($id)
    {
        //
        Post::findOrFail($id)->delete();
    }
}

resources/views/dashboard/post/create.blade.php
@extends('dashboard.app')

@section('css')
<link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
<style>
    div.components-menu-group{
        display: block !important;
    }
</style>
@endsection
@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <form enctype="multipart/form-data" method="post" action="{{ route('post.store')}}">
                @csrf
                
                <div class="form-group">
                    <div class="input-group input-group-md">
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="judul" placeholder="Judul" value="{{ old('judul') }}">
                    </div>
                </div>
                
                <div class="form-group">
                    <div class="input-group input-group-md">
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="keyword" placeholder="Keyword" value="{{ old('keyword') }}">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Kategori</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="kategori">
                        @foreach($kategori as $data)
                        <option value="{{ $data->slug }}">{{ $data->judul }}</option>
                        @endforeach
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Status </label>
                    <select class="form-control" id="exampleFormControlSelect1" name="status">
                        
                        <option value="publish">Terbitkan Sekarang</option>
                        <option value="draft">Draft / Simpan</option>
                        
                    </select>
                </div>
                
                <div class="form-group">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" name="ringkasan" placeholder="Ringkasan" required>{{ old('ringkasan') }}</textarea>
                </div>
                
                <div class="form-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" accept="image/jpeg" name="feature">
                        <label class="custom-file-label" for="customFile">Pilih gambar</label>
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="exampleInputEmail1">Kata Kunci</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="keyword">
                </div>
                
                <div class="form-group">
                    <textarea id="konten" name="konten" hidden></textarea>
                </div>
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{ asset('vendor/bs-custom-file-input/dist/bs-custom-file-input.min.js') }}"></script>
<script src="{{ asset('vendor/react/umd/react.production.min.js') }}"></script>
<script src="{{ asset('vendor/react-dom/umd/react-dom.production.min.js') }}"></script>
<script src="{{ asset('vendor/laraberg/js/laraberg.js') }}"></script>
<script>
    bsCustomFileInput.init();
    const options = {
        laravelFilemanager: {
            prefix: '/laravel-filemanager'
        }
    }
    Laraberg.init('konten', options)
</script>
@endsection

resources/views/dashboard/post/edit.blade.php
@extends('dashboard.app')

@section('css')
<link rel="stylesheet" href="{{asset('vendor/laraberg/css/laraberg.css')}}">
<style>
    div.components-menu-group{
        display: block !important;
    }
</style>
@endsection
@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    <div class="card shadow h-100 py-2">
        <div class="card-body">
            <form enctype="multipart/form-data" method="POST" action="{{ route('post.update', $post->id) }}">
                @csrf
                @method('PUT')
                
                <div class="form-group">
                    <div class="input-group input-group-md">
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="judul" placeholder="Judul" value="{{ $post->judul ?? old('judul') }}">
                    </div>
                </div>
                
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Status saat ini : {{ $post->artikel_status }} </label>
                    <select class="form-control" id="exampleFormControlSelect1" name="status" required>
                        <option value="publish">Terbitkan Sekarang</option>
                        <option value="draft">Draft / Simpan</option>
                    </select>
                </div>
                
                <div class="form-group">
                    <label for="exampleFormControlSelect1">Kategori</label>
                    <select class="form-control" id="exampleFormControlSelect1" name="kategori" required>
                        @foreach($kategori as $data)
                        <option value="{{ $data->slug }}">{{ $data->judul }}</option>
                        @endforeach
                    </select>
                </div>
                
                <div class="form-group">
                    <div class="input-group input-group-md">
                        <input type="text" class="form-control" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-lg" name="keyword" placeholder="Keyword" value="{{ $post->keyword ?? old('keyword') }}">
                    </div>
                </div>
                
                <div class="form-group">
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="5" name="ringkasan" placeholder="Ringkasan">{{ $post->tldr ?? old('ringkasan') }}</textarea>
                </div>
                
                <div class="form-group">
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" id="customFile" accept="image/jpeg" name="feature">
                        <input type="text" class="form-control" name="current_feature" hidden value="{{ $data->image_feature }}">
                        <label class="custom-file-label" for="customFile">{{ $data->image_feature }}</label>
                    </div>
                </div>
                
                
                
                <div class="form-group">
                    <textarea id="konten" name="konten" hidden>{!! $post->konten ?? old('konten') !!}</textarea>
                </div>
                
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{ asset('vendor/bs-custom-file-input/dist/bs-custom-file-input.min.js') }}"></script>
<script src="{{ asset('vendor/react/umd/react.production.min.js') }}"></script>
<script src="{{ asset('vendor/react-dom/umd/react-dom.production.min.js') }}"></script>
<script src="{{ asset('vendor/laraberg/js/laraberg.js') }}"></script>
<script>
    bsCustomFileInput.init();
    const options = {
        laravelFilemanager: {
            prefix: '/upload_file_untuk_akubagi'
        }
    }
    Laraberg.init('konten', options)
</script>
@endsection

resources/views/dashboard/post/index.blade.php
@extends('dashboard.app')

@section('css')
<link rel="stylesheet" href="{{ asset('vendor/DataTables/dataTables.bootstrap4.css') }}">
<style>
    .page-item.active .page-link {
        color: #fff;
        background-color: #0A91AB;
        border-color: #0A91AB;
    }
</style>
@endsection
@section('content')
<div class="container-fluid">
    <!-- Page Heading -->
    @if (session('status'))
    <div class="alert alert-success" role="alert">
        {{ session('status') }}
    </div>
    @endif
    
    <div class="card shadow h-100 py-2">
        

        
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nomor</th>
                            <th width="36%">Judul</th>
                            <th>Viewer</th>
                            <th width="10%">Kategori</th>
                            <th>Opsi</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{ asset('vendor/DataTables/datatables.min.js') }}"></script>
<script src="{{ asset('vendor/DataTables/dataTables.bootstrap4.min.js') }}"></script>

<script>

$(document).ready(function() {
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
    
    $('#dataTable').DataTable({
        lengthMenu: [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]],
        processing: true,
        serverSide: true,
        ajax: {
            url: "{{ route('post.index') }}",
            type: 'GET',
        },
        columns: [
            {data: 'id',name: 'id', 'visible': false},
            {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false,searchable: false},
            {data: 'judul', name: 'judul' },
            {data: 'page_counter', name: 'page_counter' },
            {data: 'kategori', name: 'kategori' },
            {data: 'action', name: 'action', orderable: false}
        ],
        order: [[0, 'desc']]
    });
    
    $('body').on('click', '#delete-user', function () {
        var user_id = $(this).data("id");
        if(confirm("Are You sure want to delete !")){
            $.ajax({
                type: "DELETE",
                url: "{{ url('dashboard/hapus') }}/"+user_id,
                success: function (data) {
                    var oTable = $('#dataTable').dataTable(); 
                    oTable.fnDraw(false);
                    console.log('Sukses !');
                },
                error: function (data) {
                    console.log('Error:', data);
                }
            });
        }
    });
    
});

</script>
@endsection